### ISSUE TITLE
datファイルが読み込まれない件

### ISSUE THREAD

**Issue by Shirakami701** [128na/simu_addon_uploader#1]
読み込むdatファイルにおいて、「name=〇〇」行の「name」が大文字で入力されているとアドオン名が読み込まれません。

AddonAnalyzer.php 35行目
「$reg = '/name=(.*)/';」を
「$reg = '/name=(.*)/i';」にすると、大文字小文字の区別なく読み込めるようになると思います。

修正の程、宜しくお願い致します。

**Comment by 128na** [comment]
`copyright` も同様っぽかったので合わせて修正しました
