### ISSUE TITLE
CR+LF改行に対する対応

### ISSUE THREAD

**Issue by Shirakami701** [128na/simu_addon_uploader#2]
アップロードしたdatファイルやtabファイルがCR+LFで改行されていると、正確に処理できないようです。
処理前に改行文字をそろえれば、正確に処理できると思われます。

AddonAnalyzer.phpを下記のように変更して頂けますでしょうか。

25行目の前に追加
$tabs = str_replace(array('\r\n','\r','\n'), '\n', $content);

59行目を変更
$tabs = explode("\n", $content);
　↓
$tabs = str_replace(array('\r\n','\r','\n'), '\n', $content);
$tabs = explode("\n", $tabs);

以上、宜しくお願い致します。

**Comment by 128na** [comment]
修正しますた
